### ISSUE TITLE
Admin pages can not sort by table header

### ISSUE THREAD

**Issue by jifffffy** [opengreenfield/greenfield#1]
Hi, I am learning Grails, I find this project is great!
I have run successfully! but I find these tables  of  admin pages can not be sorted by clicking table header.

![bae1 8bi 48t2 j8wx ri b](https://user-images.githubusercontent.com/5210372/35367739-f4761eb2-01ba-11e8-8525-6ea626a8db1d.png)

I have another question : When to modify the product price does not affect the price of the order? If the user has paid successfully,  I think  price of the order should not be changed.  I can not test this by paying.

**Comment by mcroteau** [comment]
Great! Thank you.
