### ISSUE TITLE
how to check admin role

### ISSUE THREAD

**Issue by nikhil-shrestha** [opengreenfield/greenfield#3]
need to check role on getAdminLink() on ApplicationService.groovy

**Comment by nikhil-shrestha** [comment]
Subject subject = SecurityUtils.getSubject()

if (subject.hasRole('ROLE_ADMIN')) {
            return "<a href=\"/${getContextName()}/admin\" id=\"admin-link\">Administration</a>"
 } else {
          return ""
 }

**Comment by mcroteau** [comment]
Thank you. Issue is resolved, used Spring Security Core's authority check to determine if has administrator role.

**Comment by mcroteau** [comment]
Thank you. Issue is resolved, used Spring Security Core's authority check to determine if has administrator role.
